"$schema" = "./node_modules/wrangler/config-schema.json"
name = "ch0wn3rs"
compatibility_date = "2026-03-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "CTFTIME_KV"
id = "8172b4afb6fa4352bc6469c21420a2b3"

[[kv_namespaces]]
binding = "SESSION"
id = "bd6d3a781bdf47bea4238b5d7ac537f8"
